### ISSUE TITLE
Update "TinkerPop" references to "Apache TinkerPop"

### ISSUE THREAD

**Issue by spmallette** [orientechnologies/orientdb-gremlin#109]
Please update references to "TinkerPop" or "TP3" to include the prefix of "Apache" so as to acknowledge Apache trademarks. I can offer a pull request if you'd like me to help out (simple change to README - just let me know) but the GitHub project description would be something to update on your end obviously.

**Comment by luigidellaquila** [comment]
Hi @spmallette 

Thank you very much for pointing this out. A PR will be very appreciated

Thanks

Luigi

**Comment by spmallette** [comment]
Sorry - i got distracted a bit and just came back to offer the PR when I noticed that the update has already been made. README looks good now. An edit to the GitHub project description would be nice too, but a PR can't fix that. Thanks for making that change.
