### ISSUE TITLE
Determining if a Vertex or Edge has been modified? 

### ISSUE THREAD

**Issue by fppt** [orientechnologies/orientdb-gremlin#118]
Hello Again,

Is there a way to know if a Vertex or Edge has been modified? 

For example TitanDB has `TitanVertex#isModified()`. Is there anything similar ? I can't find anything in `OrientVertex` or `OrientElement`.

Can anyone point me as to how I may implement this if needs be?

Thanks,

Filipe

**Comment by lvca** [comment]
You can use vertex.getRecord().isDirty(). If true, it has been modified. You can also access to what has been modified:
- `((ODocument)vertex.getRecord()).getDirtyFields()` returns the `String[]` of the modified fields
- `((ODocument)vertex.getRecord()).getOriginalValue(field)` returns the original value of a field

**Comment by fppt** [comment]
Thanks @lvca . That's brilliant.
