### ISSUE TITLE
Support for tinkerpop 3.3.0

### ISSUE THREAD

**Issue by stuarthendren** [orientechnologies/orientdb-gremlin#139]
When using with version 3.3.0 I get a NoSuchMethodException for 

`org.apache.tinkerpop.gremlin.structure.io.Io$Builder.registry`

Is there a plan to support 3.3.x?

**Comment by maggiolo00** [comment]
Hi @stuarthendren 

yes the support for 3.3.x will come with the Official support of Apache TinkerPop in OrientDB 3.0
