### ISSUE TITLE
Multiple relationship issue

### ISSUE THREAD

**Issue by Akshay-15mca1098** [orientechnologies/orientdb-gremlin#148]
1. Let's create 3 vertices (with no relationship) [works fine]
```
graph.addVertex(label, "Master", "title", "master")
graph.addVertex(label, "Test", "title", 'abc')
graph.addVertex(label, "Test", "title", 'xyz')
```

2. Link master with abc [ works fine]
`g.V().hasLabel("Master").addE("relation").to(g.V().has("Test","title",'abc'))`

3. Link master with xyz [Fails] 
`g.V().hasLabel("Master").addE("relation").to(g.V().has("Test","title",'xyz'))`

**ERROR**
`Cannot UPDATE the record #59:3 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2 your=v1)`

**Comment by maggiolo00** [comment]
Hi @Akshay-15mca1098 

i've just pushed a fix for this. It will be available in the next OrientDB 3.0.4 GA release.
